# Use Node.js 20.18.2 as base image
FROM node:20.18.2-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port Nuxt runs on (default is 3000)
EXPOSE 3000

# Start the app in development mode
CMD ["yarn", "dev"]
